// This worker controls the laundry URL prefix only; it never caches API/data routes.
const worker = `
const CACHE='fusion-laundry-shell-v1';
const SHELL='/demo/laundry';
const laundryPath=p=>p===SHELL||p===SHELL+'/';
const asset=u=>u.origin===self.location.origin&&u.pathname.startsWith('/_next/static/');
async function cacheShell(){const response=await fetch(SHELL,{cache:'reload',headers:{Accept:'text/html'}});if(!response.ok||!response.headers.get('content-type')?.includes('text/html'))throw Error('Laundry shell unavailable');await(await caches.open(CACHE)).put(SHELL,response);}
self.addEventListener('install',event=>event.waitUntil(cacheShell().then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil((async()=>{for(const key of await caches.keys())if(key.startsWith('fusion-laundry-shell-')&&key!==CACHE)await caches.delete(key);await self.clients.claim()})()));
self.addEventListener('message',event=>{if(event.data?.type!=='CACHE_LAUNDRY_ASSETS')return;event.waitUntil((async()=>{try{const client=await self.clients.get(event.source?.id);if(!client||!laundryPath(new URL(client.url).pathname))throw Error('Unscoped client');const cache=await caches.open(CACHE);for(const raw of [...new Set(event.data.urls||[])].slice(0,200)){const url=new URL(raw,self.location.origin);if(!asset(url))continue;if(await cache.match(url.href))continue;const response=await fetch(url.href);if(!response.ok)throw Error('Asset cache failed');await cache.put(url.href,response)}if(!await cache.match(SHELL))throw Error('Shell not cached');event.ports[0]?.postMessage({ready:true})}catch(error){event.ports[0]?.postMessage({ready:false,error:String(error)})}})())});
self.addEventListener('fetch',event=>{const url=new URL(event.request.url);if(event.request.method!=='GET'||url.origin!==self.location.origin)return;if(event.request.mode==='navigate'){if(!laundryPath(url.pathname))return;event.respondWith((async()=>{try{const response=await fetch(event.request);if(response.ok&&response.headers.get('content-type')?.includes('text/html'))await(await caches.open(CACHE)).put(SHELL,response.clone());return response}catch{const saved=await(await caches.open(CACHE)).match(SHELL);return saved||new Response('Laundry demo was not cached. Open it online once.',{status:503})}})());return}if(asset(url))event.respondWith((async()=>{const cache=await caches.open(CACHE);const saved=await cache.match(event.request);if(saved)return saved;const response=await fetch(event.request);if(response.ok)await cache.put(event.request,response.clone());return response})())});
`;
export function GET(){return new Response(worker,{headers:{'Content-Type':'application/javascript; charset=utf-8','Cache-Control':'no-cache','Service-Worker-Allowed':'/demo/laundry'}})}
