const assert=require('node:assert/strict');const { chromium }=require(process.env.PLAYWRIGHT_MODULE || 'C:/Users/USER/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const BASE=process.env.CRM_DEMO_URL || 'http://localhost:3000/demo/multi-company-crm';
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1366,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const d=()=>page.getByRole('dialog');const close=()=>page.getByRole('button',{name:'Close dialog',exact:true}).click();const st=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('fusion-multi-company-crm-demo-v1')));
await page.goto(BASE);await page.getByRole('button',{name:'Add customer',exact:true}).click();await d().locator('[name="name"]').fill('Cedar');assert(await d().getByRole('button',{name:/Cedar Events/}).isVisible());await d().getByRole('button',{name:/Cedar Events/}).click();assert(await d().getByRole('heading',{name:'Cedar Events',exact:true}).isVisible());await close();
await page.getByRole('button',{name:'Schedule meeting',exact:true}).click();await d().getByRole('checkbox',{name:'Create a customer within this meeting'}).check();for(const [k,v]of Object.entries({inlineName:'Inline Client',inlineContact:'Mira',inlineEmail:'mira@inline.example',inlineMobile:'+971555123123',inlineLocation:'Downtown Dubai',location:'Dubai meeting room'}))await d().locator(`[name="${k}"]`).fill(v);await d().getByRole('button',{name:'Save meeting',exact:true}).click();await page.waitForTimeout(100);let s=await st();const inline=s.records.customers.find(c=>c.name==='Inline Client');assert(s.records.meetings.some(m=>m.customerId===inline.id));await d().getByRole('button',{name:'Complete meeting',exact:true}).click();await d().locator('[name="notes"]').fill('Requested another visit');await d().locator('[name="nextAction"]').fill('Sample review');await d().locator('[name="followupDate"]').fill(s.records.meetings.find(m=>m.customerId===inline.id).date);await d().locator('[name="followupType"]').selectOption('Meeting');await d().getByRole('button',{name:'Complete & save follow-up'}).click();await page.waitForTimeout(100);assert.equal((await st()).records.meetings.filter(m=>m.customerId===inline.id).length,2);await close();
await page.goto(BASE+'/tasks');await page.getByRole('button',{name:'New task',exact:true}).click();await d().locator('[name="title"]').fill('Review inline opportunity');await d().locator('[name="customerId"]').selectOption(inline.id);await d().locator('[name="relatedId"]').selectOption('customers:'+inline.id);await d().getByRole('button',{name:'Save task',exact:true}).click();await page.waitForTimeout(100);const task=(await st()).records.tasks.find(t=>t.title==='Review inline opportunity');assert.equal(task.relatedId,inline.id);assert.equal(task.relatedKind,'customers');await d().getByRole('combobox',{name:'Task status'}).selectOption('Completed');await page.waitForTimeout(100);assert.equal((await st()).records.tasks.find(t=>t.id===task.id).status,'Completed');await close();
await page.goto(BASE+'/quotations');await page.locator('tbody button').filter({hasText:'QT-102'}).click();await d().getByRole('button',{name:'Convert to order',exact:true}).click();assert(await d().getByRole('heading',{name:'Operational progress'}).isVisible());await close();
await page.goto(BASE+'/opportunities');s=await st();const deal=s.records.opportunities.find(o=>o.id==='advertising-o4');const source=page.locator('article').filter({hasText:deal.title});const target=page.locator('section').filter({has:page.locator('header span').filter({hasText:/^Negotiation$/})});await source.dragTo(target);await page.waitForTimeout(200);s=await st();assert.equal(s.records.opportunities.find(o=>o.id===deal.id).stage,'Negotiation');assert.equal(s.records.opportunities.find(o=>o.id===deal.id).probability,deal.probability);
await page.goto(BASE+'/reports');await page.getByLabel('From',{exact:true}).fill('2020-01-01');await page.getByLabel('To',{exact:true}).fill('2020-01-02');await page.getByText('AED 0',{exact:true}).waitFor();
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Demo guide',exact:true}).click();assert(await d().getByRole('heading',{name:'Your demo, from enquiry to delivery'}).isVisible());await close();await page.getByRole('button',{name:'Reset Demo Data',exact:true}).click();await d().getByRole('button',{name:'Reset Demo Data',exact:true}).click();await page.waitForTimeout(150);assert(!(await st()).records.customers.some(c=>c.id===inline.id));
for(const company of ['packaging','supply']){await page.getByRole('combobox',{name:'Select company'}).selectOption(company);await page.goto(BASE+'/orders');await page.locator('tbody button').first().click();if(company==='supply'){await d().locator('[name="supplier"]').fill('Demo Supply Partner');await d().locator('[name="supplierAmount"]').fill('19000');await d().locator('[name="approval"]').selectOption('Approved');await d().getByRole('button',{name:'Save supplier details',exact:true}).click();await page.waitForTimeout(150);assert((await st()).records.orders.some(o=>o.company==='supply'&&o.supplier==='Demo Supply Partner'&&o.approval==='Approved'));}await page.screenshot({path:`scripts/crm-demo/mobile-${company}-order.png`,fullPage:true});await close();}
assert.deepEqual(errors,[]);console.log('PASS: duplicate suggestions, inline customer, follow-up meeting, task relationship and completion, approved quotation conversion, drag-and-drop with unchanged probability, date-filtered reports, mobile guide/reset, packaging/supply order layouts.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
