"use client";

import { useEffect, useRef, useState } from "react";
import Image from "next/image";
import {
  ArrowRight,
  BarChart3,
  BriefcaseBusiness,
  Check,
  ChevronDown,
  Code2,
  Database,
  Globe2,
  LayoutDashboard,
  Linkedin,
  Menu,
  MessageCircle,
  MonitorSmartphone,
  Search,
  Settings2,
  Smartphone,
  UsersRound
} from "lucide-react";
import { SiteFooter } from "@/components/site-footer";

const navItems = [
  ["Services", "#services"],
  ["CRM", "#crm"],
  ["Process", "#process"],
  ["Work", "#work"],
  ["About", "#about"],
  ["Contact", "#contact"]
] as const;

const serviceCards = [
  { title: "Websites", icon: Globe2, text: "High-performance websites designed to communicate clearly, convert visitors, and support growth.", items: ["Corporate websites", "E-commerce websites", "Landing pages", "Website redesign", "Web portals", "Performance optimisation"], tone: "from-[#e8c777]/30" },
  { title: "Apps & Web Platforms", icon: Smartphone, text: "Mobile and web applications built around real customer and operational needs.", items: ["Android applications", "iOS applications", "Web applications", "Customer portals", "Marketplace platforms", "MVP development"], tone: "from-[#9ab7e8]/30" },
  { title: "Custom CRM & Business Systems", icon: Database, text: "Custom platforms that organise teams, customers, workflows, documents, finance, and daily operations.", items: ["Lead management", "Employee management", "Tasks and approvals", "Documents and records", "Finance and invoicing", "Reports and dashboards"], tone: "from-[#b8a6e8]/30" },
  { title: "Marketing & Growth", icon: BarChart3, text: "Integrated marketing systems designed to improve visibility, generate leads, and support measurable growth.", items: ["Digital strategy", "SEO", "Social media marketing", "Paid advertising", "Content and creative", "Analytics and reporting"], tone: "from-[#7fcab7]/30" }
];

const crmModules = ["Dashboard", "Leads", "Customers", "Employees", "Attendance", "Tasks", "Documents", "Finance", "Reports"];
const processSteps = [["Discover", "Understand the business, users, challenges, and desired outcomes."], ["Plan", "Define scope, workflows, technology, and project structure."], ["Design", "Create the user journey, interface, and visual direction."], ["Develop", "Build, integrate, test, and optimise the solution."], ["Launch & Grow", "Deploy, support, measure, and improve over time."]];
const faqs = [["What type of projects does Fynta handle?", "Fynta works on websites, mobile applications, web platforms, custom CRM systems, business automation, and digital marketing projects."], ["Can you build a completely custom CRM?", "Yes. We can plan and build a CRM around your teams, workflows, permissions, documents, customers, and reporting requirements."], ["Do you work with startups?", "Yes. We help startups plan, design, and develop MVPs as well as improve and scale existing digital products."], ["Can Fynta handle both development and marketing?", "Yes. Our integrated team can support strategy, branding, design, development, launch, and digital growth."], ["Do you provide support after launch?", "Yes. Maintenance, improvements, technical support, and marketing can be provided based on project requirements."], ["Can you improve an existing website or application?", "Yes. We can audit, redesign, rebuild, or extend an existing digital product."]];

function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="text-[11px] font-bold uppercase tracking-[0.24em] text-[#d6a84f]">{children}</p>; }

function FyntaMark() { return <a href="/fynta" className="text-2xl font-semibold tracking-[-0.06em] text-white" aria-label="Fynta home">fyn<span className="text-[#d6a84f]">ta</span></a>; }

function ProductPreview({ type = "website", activeModule = "Dashboard" }: { type?: string; activeModule?: string }) {
  if (type === "crm") return <div className="overflow-hidden rounded-xl border border-white/12 bg-[#0d1017] shadow-2xl"><div className="flex h-9 items-center gap-2 border-b border-white/10 px-3 text-[8px] text-white/42"><span className="h-2 w-2 rounded-full bg-[#d6a84f]" /><span>fyn.ta / {activeModule.toLowerCase()}</span></div><div className="grid min-h-[245px] grid-cols-[68px_1fr]"><aside className="border-r border-white/10 p-3"><LayoutDashboard className="h-4 w-4 text-[#d6a84f]" /><UsersRound className="mt-5 h-4 w-4 text-white/40" /><Settings2 className="mt-5 h-4 w-4 text-white/40" /></aside><div className="p-4"><div className="flex items-center justify-between"><p className="text-sm font-semibold">{activeModule}</p><span className="h-6 w-14 rounded bg-[#d6a84f]/15" /></div><div className="mt-4 grid grid-cols-3 gap-2">{["New", "Active", "Follow-up"].map((label, i) => <div key={label} className="rounded border border-white/8 bg-white/[0.035] p-2"><p className="text-[7px] text-white/40">{label}</p><p className="mt-1 text-sm">{["24", "61", "12"][i]}</p></div>)}</div><div className="mt-4 space-y-2">{["Al Noor Trading", "Mosaic Studio", "Northline LLC"].map((name, i) => <div key={name} className="flex items-center justify-between rounded bg-white/[0.035] px-2 py-2 text-[8px]"><span>{name}</span><span className="text-[#d6a84f]">{i === 0 ? "In review" : "Updated"}</span></div>)}</div></div></div></div>;
  if (type === "marketing") return <div className="rounded-xl border border-white/12 bg-[#0d1017] p-4 shadow-2xl"><div className="flex items-center justify-between"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-white/52">Campaign overview</p><span className="rounded bg-[#d6a84f]/15 px-2 py-1 text-[8px] text-[#e8c777]">Live</span></div><div className="mt-5 grid grid-cols-[1fr_94px] gap-4"><div><p className="text-2xl font-medium">Growth signals</p><svg viewBox="0 0 210 90" className="mt-4 h-24 w-full"><polyline points="4,80 34,68 60,73 87,43 118,56 150,28 178,37 206,10" fill="none" stroke="#d6a84f" strokeWidth="2.4" /><path d="M4 80H206" stroke="rgba(255,255,255,.12)" /></svg></div><div className="space-y-2">{["SEO", "Social", "Ads"].map((label, i) => <div key={label} className="rounded border border-white/10 bg-white/[0.035] p-2 text-[8px]"><p className="text-white/45">{label}</p><p className="mt-1 text-sm">{["38", "27", "16"][i]}</p></div>)}</div></div></div>;
  if (type === "apps") return <div className="flex min-h-[278px] items-end justify-center gap-6 rounded-xl border border-white/12 bg-[#0d1017] p-5 shadow-2xl"><div className="h-[220px] w-[108px] rounded-[18px] border-[5px] border-[#252a36] bg-[#f2eee6] p-3 text-[#15120e]"><div className="h-1.5 w-10 rounded bg-black/15" /><p className="mt-5 text-[10px] font-bold">Welcome back</p><div className="mt-4 h-16 rounded-md bg-[#d6a84f]/60" /><div className="mt-3 grid grid-cols-2 gap-2"><span className="h-8 rounded bg-black/8" /><span className="h-8 rounded bg-black/8" /></div></div><div className="hidden w-[220px] rounded border border-white/10 bg-white/[0.04] p-3 sm:block"><p className="text-[8px] text-white/48">Customer portal</p><div className="mt-3 grid grid-cols-3 gap-2">{[1,2,3].map(i => <span key={i} className="h-12 rounded bg-white/[0.07]" />)}</div><div className="mt-3 h-20 rounded bg-[#d6a84f]/12" /></div></div>;
  return <div className="rounded-xl border border-white/12 bg-[#0d1017] p-3 shadow-2xl"><div className="flex h-6 items-center gap-1.5 border-b border-white/10 px-1"><span className="h-1.5 w-1.5 rounded-full bg-[#d6a84f]" /><span className="h-1.5 w-1.5 rounded-full bg-white/24" /></div><div className="mt-3 grid min-h-[230px] grid-cols-[42%_58%]"><div className="p-3"><p className="text-[8px] uppercase tracking-[.2em] text-[#d6a84f]">Digital clarity</p><h4 className="mt-4 text-xl font-medium">Built for the next move.</h4><span className="mt-7 block h-7 w-20 bg-[#d6a84f]" /></div><div className="bg-[linear-gradient(135deg,rgba(214,168,79,.36),rgba(255,255,255,.05))] p-3"><div className="h-full rounded border border-white/20 bg-black/15" /></div></div></div>;
}

export default function FyntaClient() {
  const [activeModule, setActiveModule] = useState("Dashboard");
  const [activeProcess, setActiveProcess] = useState(0);
  const pageRef = useRef<HTMLElement>(null);

  useEffect(() => {
    const sections = Array.from(pageRef.current?.querySelectorAll<HTMLElement>(":scope > section") ?? []);
    const reducedMotion = window.matchMedia("(prefers-reduced-motion: reduce)");

    if (reducedMotion.matches) {
      sections.forEach((section) => section.classList.add("is-visible"));
      return;
    }

    sections.forEach((section, index) => {
      section.classList.add("scroll-reveal");
      section.style.transitionDelay = `${Math.min(index % 3, 2) * 70}ms`;
    });

    const observer = new IntersectionObserver(
      (entries) => entries.forEach((entry) => {
        if (!entry.isIntersecting) return;
        entry.target.classList.add("is-visible");
        observer.unobserve(entry.target);
      }),
      { threshold: 0.12, rootMargin: "0px 0px -48px" }
    );

    sections.forEach((section) => observer.observe(section));
    return () => observer.disconnect();
  }, []);

  return <main ref={pageRef} className="min-h-screen overflow-hidden bg-[#070808] text-white">
    <header className="sticky top-0 z-50 border-b border-white/10 bg-[#070808]/92 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-[1440px] items-center justify-between px-5 sm:px-10 lg:px-14"><FyntaMark /><nav className="hidden items-center gap-6 lg:flex">{navItems.slice(0,5).map(([label, href]) => <a key={label} href={href} className="text-[10px] font-bold uppercase tracking-[.12em] text-white/62 transition hover:text-[#e8c777]">{label}</a>)}</nav><a href="#contact" className="hidden bg-[#d6a84f] px-5 py-3 text-[10px] font-bold uppercase tracking-[.12em] text-black transition hover:bg-[#e8c777] sm:inline-flex">Discuss Your Project</a><Menu className="h-5 w-5 text-[#d6a84f] sm:hidden" /></div></header>

    <section className="relative border-b border-white/10 px-5 pb-20 pt-16 sm:px-10 lg:px-14 lg:pb-28 lg:pt-24"><div className="pointer-events-none absolute inset-x-0 top-0 h-full bg-[radial-gradient(circle_at_72%_38%,rgba(214,168,79,.16),transparent_25%),radial-gradient(circle_at_30%_0%,rgba(255,255,255,.05),transparent_30%)]" /><div className="relative mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[46%_54%] lg:items-center"><div><Eyebrow>Digital Solutions by Fusion Ventures</Eyebrow><h1 className="mt-6 max-w-[650px] text-5xl font-medium leading-[.96] tracking-[-.06em] sm:text-6xl lg:text-7xl">We build digital systems that move businesses forward.</h1><p className="mt-7 max-w-[590px] text-base leading-8 text-white/64 sm:text-lg">Websites, mobile apps, custom CRM platforms, and digital marketing—planned, designed, and developed by one integrated team.</p><div className="mt-9 flex flex-wrap gap-4"><a href="#contact" className="inline-flex items-center gap-3 bg-[#d6a84f] px-6 py-4 text-xs font-bold uppercase tracking-[.1em] text-black transition hover:bg-[#e8c777]">Discuss Your Project <ArrowRight className="h-4 w-4" /></a><a href="#services" className="inline-flex items-center gap-3 border border-white/20 px-6 py-4 text-xs font-bold uppercase tracking-[.1em] text-white/78 transition hover:border-[#d6a84f] hover:text-[#e8c777]">Explore Our Services <ArrowRight className="h-4 w-4" /></a></div></div><div className="relative mx-auto w-full max-w-[760px] overflow-hidden rounded-xl border border-white/12 shadow-[0_28px_80px_rgba(0,0,0,.55)]"><Image src="/fynta/fynta-hero-ecosystem.png" alt="Connected website, mobile app, CRM, and analytics interfaces" width={1600} height={1000} priority className="h-auto w-full" /></div></div></section>

    <section className="border-b border-white/10 px-5 py-5 sm:px-10 lg:px-14"><div className="mx-auto flex max-w-[1280px] flex-wrap justify-between gap-x-8 gap-y-4 text-[10px] font-bold uppercase tracking-[.16em] text-white/48">{["Strategy", "UI/UX Design", "Development", "Automation", "Marketing", "Ongoing Support"].map(item => <span key={item} className="flex items-center gap-3"><span className="h-1.5 w-1.5 rounded-full bg-[#d6a84f]" />{item}</span>)}</div></section>

    <section id="services" className="px-5 py-20 sm:px-10 lg:px-14 lg:py-28"><div className="mx-auto max-w-[1280px]"><Eyebrow>What We Do</Eyebrow><h2 className="mt-5 max-w-[780px] text-4xl font-medium tracking-[-.05em] sm:text-5xl">Everything your business needs to build, operate, and grow digitally.</h2><div className="mt-12 grid gap-5 lg:grid-cols-2">{serviceCards.map((card, index) => { const Icon = card.icon; return <article key={card.title} className="group relative overflow-hidden border border-white/12 bg-[#0d0f13] p-6 transition duration-500 hover:-translate-y-1 hover:border-[#d6a84f]/55 sm:p-8"><div className={`pointer-events-none absolute inset-x-0 top-0 h-36 bg-gradient-to-b ${card.tone} to-transparent opacity-0 transition-opacity duration-500 group-hover:opacity-100`} /><div className="relative grid gap-7 sm:grid-cols-[1fr_45%] sm:items-start"><div><Icon className="h-7 w-7 text-[#d6a84f]" strokeWidth={1.5} /><p className="mt-7 text-[10px] font-bold tracking-[.16em] text-white/38">0{index + 1}</p><h3 className="mt-2 text-3xl font-medium tracking-[-.04em]">{card.title}</h3><p className="mt-4 max-w-md text-sm leading-7 text-white/60">{card.text}</p><ul className="mt-6 grid grid-cols-2 gap-x-3 gap-y-2 text-[10px] leading-4 text-white/52">{card.items.map(item => <li key={item} className="flex gap-2"><Check className="h-3.5 w-3.5 shrink-0 text-[#d6a84f]" />{item}</li>)}</ul></div><ProductPreview type={index === 0 ? "website" : index === 1 ? "apps" : index === 2 ? "crm" : "marketing"} /></div></article>; })}</div></div></section>

    <section className="border-y border-white/10 bg-[#0c0d0f] px-5 py-20 sm:px-10 lg:px-14 lg:py-28"><div className="mx-auto max-w-[1280px]"><Eyebrow>Built Around Your Business</Eyebrow><h2 className="mt-5 text-4xl font-medium tracking-[-.05em] sm:text-5xl">Built around your business—not around a template.</h2><div className="mt-12 grid gap-px bg-white/10 md:grid-cols-2 lg:grid-cols-3">{[["Leads are scattered", "A custom CRM brings enquiries, follow-ups, assignments, and reporting into one system."], ["Your website no longer represents the business", "A high-performance website clarifies your offer and makes the right next step easy."], ["Customers need an easier way to order or book", "A focused mobile or web product creates a smoother customer journey."], ["Teams repeat manual tasks every day", "Connected workflows and automation reduce operational friction."], ["Different tools are not connected", "Business systems and APIs can make information flow where it needs to."], ["Marketing lacks clear direction", "A joined-up growth plan connects content, search, paid media, and measurement."]].map(([problem, solution]) => <article key={problem} className="bg-[#0c0d0f] p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.13em] text-white/42">Problem</p><h3 className="mt-4 text-xl font-medium">{problem}</h3><div className="my-6 h-px w-12 bg-[#d6a84f]" /><p className="text-xs font-bold uppercase tracking-[.13em] text-[#d6a84f]">Fynta solution</p><p className="mt-3 text-sm leading-7 text-white/58">{solution}</p></article>)}</div></div></section>

    <section id="crm" className="px-5 py-20 sm:px-10 lg:px-14 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[38%_62%] lg:items-center"><div><Eyebrow>Custom CRM Development</Eyebrow><h2 className="mt-5 text-4xl font-medium leading-[1.02] tracking-[-.05em] sm:text-5xl">Your business should not have to adapt to generic software.</h2><p className="mt-6 text-base leading-8 text-white/62">We build custom CRM and operations platforms around the way your organisation works—from leads and employees to customers, documents, finance, approvals, and reporting.</p><a href="#contact" className="mt-8 inline-flex items-center gap-3 text-xs font-bold uppercase tracking-[.12em] text-[#e8c777]">Discuss a Custom CRM <ArrowRight className="h-4 w-4" /></a></div><div className="overflow-hidden border border-white/12 bg-[#10131a] p-4 sm:p-6"><div className="no-scrollbar flex gap-2 overflow-x-auto border-b border-white/10 pb-4">{crmModules.map(module => <button key={module} type="button" onClick={() => setActiveModule(module)} className={`shrink-0 border px-3 py-2 text-[10px] font-bold uppercase tracking-[.1em] transition ${activeModule === module ? "border-[#d6a84f] bg-[#d6a84f] text-black" : "border-white/12 text-white/52 hover:border-white/35"}`}>{module}</button>)}</div><div className="mt-5"><ProductPreview type="crm" activeModule={activeModule} /></div></div></div></section>

    <section id="process" className="border-y border-white/10 bg-[#0c0d0f] px-5 py-20 sm:px-10 lg:px-14 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[36%_64%]"><div><Eyebrow>Our Process</Eyebrow><h2 className="mt-5 text-4xl font-medium tracking-[-.05em] sm:text-5xl">From the first idea to launch and growth.</h2><p className="mt-5 text-sm leading-7 text-white/58">A clear working rhythm keeps every decision connected to the business outcome.</p></div><div className="grid gap-px bg-white/10 sm:grid-cols-5">{processSteps.map(([title, text], i) => <button type="button" key={title} onClick={() => setActiveProcess(i)} className={`min-h-[220px] p-5 text-left transition ${activeProcess === i ? "bg-[#d6a84f] text-black" : "bg-[#0c0d0f] text-white hover:bg-white/[.04]"}`}><span className={`text-[10px] font-bold tracking-[.16em] ${activeProcess === i ? "text-black/55" : "text-[#d6a84f]"}`}>0{i + 1}</span><h3 className="mt-9 text-xl font-medium">{title}</h3><p className={`mt-4 text-xs leading-6 ${activeProcess === i ? "text-black/70" : "text-white/52"}`}>{text}</p></button>)}</div></div></section>

    <section className="px-5 py-20 sm:px-10 lg:px-14 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[38%_62%]"><div><Eyebrow>Why Fynta</Eyebrow><h2 className="mt-5 text-4xl font-medium tracking-[-.05em] sm:text-5xl">One team for strategy, design, technology, and growth.</h2></div><div className="grid gap-px bg-white/10 sm:grid-cols-2">{[["One integrated team", "Design, development, CRM, automation, and marketing are planned together."], ["Built around your workflow", "We do not force every business into the same template or software structure."], ["Strategy before execution", "Projects begin with understanding the business, users, and objectives."], ["Designed to scale", "Solutions are planned to support new users, teams, services, and locations."], ["Support beyond launch", "We can maintain, improve, and market the solution after it goes live."]].map(([title, text]) => <article key={title} className="bg-[#070808] p-6"><h3 className="text-lg font-medium">{title}</h3><p className="mt-3 text-sm leading-7 text-white/55">{text}</p></article>)}</div></div></section>

    <section className="border-y border-white/10 bg-[#0c0d0f] px-5 py-20 sm:px-10 lg:px-14 lg:py-28"><div className="mx-auto max-w-[1280px]"><Eyebrow>Solutions for Growth</Eyebrow><h2 className="mt-5 text-4xl font-medium tracking-[-.05em] sm:text-5xl">Solutions for different stages of business growth.</h2><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[["Startups launching an MVP", "Shape the first focused version of a digital product."], ["Growing businesses replacing spreadsheets", "Move leads, customers, teams, and reports into one connected system."], ["Companies requiring custom CRM systems", "Build operations software around established workflows."], ["Retail and e-commerce businesses", "Create clearer journeys from discovery to order management."], ["Professional service businesses", "Make enquiries, delivery, and client communication easier to manage."], ["Companies modernising old systems", "Improve existing technology without losing business context."]].map(([title, text], i) => <article key={title} className="border border-white/12 p-6"><span className="text-[10px] font-bold tracking-[.16em] text-[#d6a84f]">0{i+1}</span><h3 className="mt-6 text-xl font-medium">{title}</h3><p className="mt-4 text-sm leading-7 text-white/55">{text}</p></article>)}</div></div></section>

    <section id="work" className="px-5 py-20 sm:px-10 lg:px-14 lg:py-28"><div className="mx-auto max-w-[1280px]"><Eyebrow>Selected Work</Eyebrow><h2 className="mt-5 text-4xl font-medium tracking-[-.05em] sm:text-5xl">Digital products and systems we have helped build.</h2><div className="mt-12 grid gap-5 lg:grid-cols-4">{[["BSmile CRM", "Custom CRM / Internal Operations", "Employee, patient, document, and finance management platform.", "crm"], ["KAAM", "Mobile App / Web Platform", "Candidate and employer job-matching platform for the UAE.", "apps"], ["Aweer Market", "Mobile Application / Commerce", "B2B ordering with catalogue, wallet, and order management.", "apps"], ["Resumi", "Web Application / SaaS", "Online resume-building tools with ATS-focused templates.", "website"]].map(([title, category, text, type]) => <article key={title} className="border border-white/12 bg-[#0d0f13] p-4"><ProductPreview type={type} /><p className="mt-5 text-[9px] font-bold uppercase tracking-[.15em] text-[#d6a84f]">{category}</p><h3 className="mt-3 text-xl font-medium">{title}</h3><p className="mt-3 text-sm leading-6 text-white/55">{text}</p></article>)}</div></div></section>

    <section className="border-y border-white/10 bg-[#0c0d0f] px-5 py-16 sm:px-10 lg:px-14"><div className="mx-auto grid max-w-[1280px] gap-10 lg:grid-cols-[30%_70%]"><div><Eyebrow>Technology</Eyebrow><h2 className="mt-5 text-3xl font-medium tracking-[-.05em] sm:text-4xl">Modern technology selected for the project—not for the trend.</h2></div><div className="grid gap-px bg-white/10 sm:grid-cols-2 lg:grid-cols-4">{[["Web", "Next.js · React · WordPress"], ["Mobile", "Flutter · Android · iOS"], ["Backend & data", "Supabase · APIs · authentication"], ["Infrastructure & growth", "Vercel · Cloudflare · Google · Meta · SEO tools"]].map(([label, stack]) => <div key={label} className="bg-[#0c0d0f] p-5"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#d6a84f]">{label}</p><p className="mt-4 text-sm leading-6 text-white/60">{stack}</p></div>)}</div></div></section>

    <section id="about" className="px-5 py-20 sm:px-10 lg:px-14 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-10 border border-white/12 p-7 sm:p-10 lg:grid-cols-[55%_45%] lg:items-center"><div><Eyebrow>Part of Fusion Ventures</Eyebrow><h2 className="mt-5 text-4xl font-medium tracking-[-.05em] sm:text-5xl">Technology, creativity, and growth under one ecosystem.</h2><p className="mt-6 max-w-2xl text-base leading-8 text-white/60">Fynta is the digital solutions and growth division of Fusion Ventures. We work with businesses and emerging ventures to transform ideas, operations, and customer experiences through practical digital solutions.</p><p className="mt-4 max-w-2xl text-base leading-8 text-white/60">Our team brings together strategy, design, development, automation, and marketing to create systems that are useful, scalable, and built around real business needs.</p><a href="/about" className="mt-7 inline-flex items-center gap-3 text-xs font-bold uppercase tracking-[.12em] text-[#e8c777]">Discover Fusion Ventures <ArrowRight className="h-4 w-4" /></a></div><div className="grid min-h-56 place-items-center border border-white/10 bg-[radial-gradient(circle_at_center,rgba(214,168,79,.18),transparent_28%)]"><div className="text-center"><p className="text-4xl font-semibold tracking-[-.07em]">fyn<span className="text-[#d6a84f]">ta</span></p><span className="mx-auto mt-5 block h-12 w-px bg-[#d6a84f]" /><p className="mt-5 text-xs font-bold uppercase tracking-[.16em] text-white/56">Fusion Ventures</p></div></div></div></section>

    <section className="border-t border-white/10 px-5 py-20 sm:px-10 lg:px-14 lg:py-28"><div className="mx-auto max-w-[920px]"><Eyebrow>FAQ</Eyebrow><h2 className="mt-5 text-4xl font-medium tracking-[-.05em] sm:text-5xl">Clear answers before we begin.</h2><div className="mt-10 border-t border-white/12">{faqs.map(([question, answer]) => <details key={question} className="group border-b border-white/12 py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 text-base font-medium outline-none marker:content-none focus-visible:text-[#e8c777]">{question}<ChevronDown className="h-5 w-5 shrink-0 text-[#d6a84f] transition group-open:rotate-180" /></summary><p className="max-w-3xl pt-4 text-sm leading-7 text-white/58">{answer}</p></details>)}</div></div></section>

    <section id="contact" className="border-y border-white/10 bg-[radial-gradient(circle_at_82%_35%,rgba(214,168,79,.2),transparent_23%),#0c0d0f] px-5 py-20 sm:px-10 lg:px-14 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-10 lg:grid-cols-[62%_38%] lg:items-end"><div><Eyebrow>Let&apos;s Build</Eyebrow><h2 className="mt-5 max-w-3xl text-5xl font-medium leading-[.98] tracking-[-.06em] sm:text-6xl">Have a website, app, CRM, or growth challenge?</h2><p className="mt-6 max-w-2xl text-base leading-8 text-white/62">Tell us what you are trying to build—or what is currently not working. We&apos;ll help you identify the right next step.</p></div><div className="flex flex-wrap gap-4 lg:justify-end"><a href="mailto:info@fusionventuresglobal.com" className="inline-flex items-center gap-3 bg-[#d6a84f] px-6 py-4 text-xs font-bold uppercase tracking-[.1em] text-black transition hover:bg-[#e8c777]">Discuss Your Project <ArrowRight className="h-4 w-4" /></a><a href="https://wa.me/971542763828" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-3 border border-white/22 px-6 py-4 text-xs font-bold uppercase tracking-[.1em] text-white/80 transition hover:border-[#d6a84f] hover:text-[#e8c777]"><MessageCircle className="h-4 w-4" />WhatsApp Our Team</a></div></div></section>
    <SiteFooter />
  </main>;
}
