'use client';
import { Receipt, Wallet, CircleDollarSign, Clock, ArrowDownLeft, ArrowUpRight } from 'lucide-react';
import ReportingRangePicker,{rangeDays,withinRange,rangeLabel,type ReportingRange} from './ReportingRange';
import { report, businessDay, money, type State } from './model';
import s from './laundry.module.css';
export default function Accounting({state,range,setRange,addExpense,reviewInvoice,navigate}:{state:State;range:ReportingRange;setRange:(r:ReportingRange)=>void;addExpense:()=>void;reviewInvoice:(id:string)=>void;navigate:(v:string)=>void}){
 const values=report(state,state.branch,range.from,range.to),orders=state.orders.filter(o=>o.branch===state.branch),expenses=state.expenses.filter(e=>e.branch===state.branch&&withinRange(e.at,range));
 const cost=expenses.reduce((a,e)=>a+e.amount,0),net=values.collected-cost;
 const payments=orders.flatMap(o=>o.payments.filter(p=>withinRange(p.at,range)).map(p=>({...p,order:o}))).sort((a,b)=>b.at.localeCompare(a.at));
 const days=rangeDays(range),series=days.map(day=>({...report(state,state.branch,day,day),day,expense:expenses.filter(e=>businessDay(e.at)===day).reduce((a,e)=>a+e.amount,0)}));
 const ceiling=Math.ceil(Math.max(1,...series.flatMap(v=>[v.billed,v.collected,v.expense]))/10)*10;
 const x=(i:number)=>52+(i+.5)*570/days.length,y=(n:number)=>224-n/ceiling*178;
 const metrics=[{label:'Billed',value:values.billed,detail:'Invoices created in range',Icon:Receipt,color:'#188a7e'},{label:'Collected',value:values.collected,detail:`${payments.length} local payment ${payments.length===1?'entry':'entries'}`,Icon:Wallet,color:'#416cb1'},{label:'Operating expenses',value:cost,detail:`${expenses.length} local expense ${expenses.length===1?'entry':'entries'}`,Icon:CircleDollarSign,color:'#926617'},{label:'Pending on period invoices',value:values.pending,detail:'Current unpaid balance of this cohort',Icon:Clock,color:'#a54e69'}];
 function paymentTable(rows:typeof payments){return <div className={s.table}><table><thead><tr><th>Invoice / customer</th><th>Date & method</th><th>Amount</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td data-label="Invoice / customer"><button className={s.invoiceLink} onClick={()=>reviewInvoice(p.order.id)}>{p.order.id}</button><small>{state.customers.find(c=>c.id===p.order.customerId)?.name}</small></td><td data-label="Date & method">{businessDay(p.at)}<small>{p.method}</small></td><td data-label="Amount"><b>{money(p.amount)}</b></td></tr>)}</tbody></table></div>}
 return <div className={s.accounting}>
 <div className={s.accountingControls}><div><h2>{state.branch} financial overview</h2><p>Local branch records · Bahrain dates</p></div><ReportingRangePicker range={range} onChange={setRange}/></div>
 <div className={s.accountingMetrics}>{metrics.map(m=><section key={m.label} data-accounting-metric={m.label}><div className={s.accountMetricTitle}><span>{m.label}</span><m.Icon size={19} style={{color:m.color}}/></div><strong><small>BHD</small>{money(m.value).replace(/^BHD\s*/,'')}</strong><p>{m.detail}</p></section>)}</div>
 <div className={s.accountingChartGrid}><section className={s.dashboardPanel}><header><div><h2>Billing & cash activity</h2><p>{rangeLabel(range)} · BHD</p></div><span className={s.badge}>{days.length} {days.length===1?'day':'days'}</span></header><div className={s.plot}><svg viewBox="0 0 650 270" role="img" aria-label={`Accounting billed, collected and expenses for ${state.branch}, ${rangeLabel(range)}`}>
 {[0,1,2,3,4].map(i=>{const n=ceiling*i/4;return <g key={i}><line x1="52" x2="622" y1={y(n)} y2={y(n)} stroke="#e5ecee" strokeDasharray="3 5"/><text x="42" y={y(n)+4} textAnchor="end">{n.toFixed(0)}</text></g>})}
 {days.length===1?<>{[['Billed',series[0].billed,'#32aaa0'],['Collected',series[0].collected,'#5183d0'],['Expenses',series[0].expense,'#c59740']].map(([label,raw,color],i)=>{const value=Number(raw),center=148+i*190;return <g key={label}><rect data-account-billed={i===0?value:undefined} x={center-30} y={y(value)} width="60" height={Math.max(2,224-y(value))} rx="4" fill={String(color)}/><text x={center} y={Math.max(28,y(value)-12)} textAnchor="middle">{money(value)}</text><text x={center} y="248" textAnchor="middle">{label}</text></g>})}</>:<>{series.map((v,i)=><rect key={v.day} data-account-billed={v.billed} x={x(i)-Math.min(24,400/days.length)/2} y={y(v.billed)} width={Math.min(24,400/days.length)} height={224-y(v.billed)} rx="3" fill="#32aaa0"><title>{v.day}: billed {money(v.billed)}</title></rect>)}
 {(['collected','expense'] as const).map((field,index)=><g key={field}><polyline points={series.map((v,i)=>`${x(i)},${y(v[field])}`).join(' ')} fill="none" stroke={index?'#c59740':'#5183d0'} strokeWidth="2.5"/>{series.map((v,i)=><circle key={v.day} cx={x(i)} cy={y(v[field])} r="2.5" fill={index?'#c59740':'#5183d0'}><title>{v.day}: {field} {money(v[field])}</title></circle>)}</g>)}
 {series.filter((_,i)=>days.length<=7||i%Math.ceil(days.length/6)===0||i===days.length-1).map(v=><text key={v.day} x={x(days.indexOf(v.day))} y="248" textAnchor="middle">{v.day.slice(5)}</text>)}</>}
 </svg><div className={s.legend}>{[['Billed','#32aaa0'],['Collected','#5183d0'],['Expenses','#c59740']].map(([label,color])=><span key={label}><i style={{background:color}}/>{label}</span>)}</div>{!values.billed&&!values.collected&&!cost&&<p className={s.accountEmptyNote}>No financial activity in these dates. Change the reporting period to review other local records.</p>}</div></section>
 <section className={s.cashSummary}><div className={s.cashTitle}><Wallet size={21}/><h2>Cash movement</h2></div><span>Applied reporting period</span><strong>{money(net)}</strong><p>Collections minus entered expenses</p><div className={s.cashEquation}><div><ArrowDownLeft size={16}/><span>Collected</span><b>{money(values.collected)}</b></div><div><ArrowUpRight size={16}/><span>Expenses</span><b>{money(cost)}</b></div></div><small>This is local cash movement, not statutory profit or a bank balance. Payments and backend sync are simulated.</small></section></div>
 <div className={s.accountingLedgerGrid}><section className={s.dashboardPanel}><header><div><h2>Payment ledger</h2><p>{payments.length} {payments.length===1?'entry':'entries'} in the applied dates</p></div><span className={s.accountCount}>{payments.length}</span></header>{payments.length?<>{paymentTable(payments.slice(0,6))}{payments.length>6&&<details className={s.accountMore}><summary>Show {payments.length-6} more payment entries</summary>{paymentTable(payments.slice(6))}</details>}</>:<div className={s.accountEmpty}><Wallet size={25}/><h3>No payments in this period</h3><p>Recorded payments appear here by payment date.</p><button onClick={()=>navigate('Billing')}>Review invoices</button></div>}</section>
 <section className={s.dashboardPanel}><header><div><h2>Expense ledger</h2><p>Operating costs entered locally</p></div><button onClick={addExpense}>Add sample expense</button></header>{expenses.length?<div className={s.expenseList}>{expenses.slice().sort((a,b)=>b.at.localeCompare(a.at)).map(e=><div key={e.id}><div className={s.expenseIcon}><ArrowUpRight size={17}/></div><div><b>{e.description}</b><small>{businessDay(e.at)}</small></div><strong>{money(e.amount)}</strong></div>)}<div className={s.expenseTotal}><span>Period total</span><b>{money(cost)}</b></div></div>:<div className={s.accountEmpty}><CircleDollarSign size={25}/><h3>No expenses in this period</h3><p>Add a sample cost or choose another date range.</p><button onClick={addExpense}>Add sample expense</button></div>}</section></div>
 <details className={s.reportDetails}><summary>Daily billing breakdown · {days.length} {days.length===1?'date':'dates'}</summary><div className={s.table}><table><thead><tr><th>Bahrain date</th><th>Billed</th><th>Collected</th><th>Expenses</th></tr></thead><tbody>{series.map(v=><tr key={v.day}><td data-label="Bahrain date">{v.day}</td><td data-label="Billed">{money(v.billed)}</td><td data-label="Collected">{money(v.collected)}</td><td data-label="Expenses">{money(v.expense)}</td></tr>)}</tbody></table></div></details>
 <p className={s.accountingFootnote}>Billed follows invoice creation date; collections and expenses follow their transaction dates. Pending is the current balance on invoices created in the range. Synthetic BHD figures, illustrative tax and local records only; not globally current.</p>
 </div>;
}
