'use client';
import { Receipt, Wallet, Package, Truck, CircleDollarSign } from 'lucide-react';
import { report, businessDay, money, totals, stages, services, type State } from './model';
import s from './laundry.module.css';
import ReportingRangePicker, {rangeDays,rangeLabel,withinRange,type ReportingRange} from './ReportingRange';
const colors=['#32aaa0','#5183d0','#9471d9','#e2ad50','#db778b','#879ba9'];
export default function Dashboard({state,range,setRange,navigate,openOrder}:{state:State;range:ReportingRange;setRange:(r:ReportingRange)=>void;navigate:(v:string)=>void;openOrder:(id:string)=>void}){
 const orders=state.orders.filter(o=>o.branch===state.branch),expenses=state.expenses.filter(e=>e.branch===state.branch);
 const days=rangeDays(range),period=days.length,label=rangeLabel(range);
 const series=days.map(day=>({...report(state,state.branch,day,day),day}));
 const values=report(state,state.branch,days[0],days[days.length-1]);
 const cohort=orders.filter(o=>withinRange(o.history[0].at,range));
 const cost=expenses.filter(e=>withinRange(e.at,range)).reduce((a,e)=>a+e.amount,0);
 const active=orders.filter(o=>o.status!=='Delivered'),ready=orders.filter(o=>o.status==='Ready');
 const max=Math.max(1,...series.flatMap(v=>[v.billed,v.collected]));const ceiling=Math.ceil(max/10)*10;
 const x=(i:number)=>52+(i+.5)*570/period,y=(n:number)=>224-n/ceiling*178;
 const spark=(field:'billed'|'collected')=>series.map((v,i)=>`${8+i*144/Math.max(1,period-1)},${42-v[field]/max*34}`).join(' ');
 const mix=services.map(service=>cohort.reduce((a,o)=>a+o.items.filter(i=>i.service===service.name).reduce((b,i)=>b+i.quantity,0),0));const garments=mix.reduce((a,n)=>a+n,0);let offset=0;
 const metrics=[{label:'Billing',value:money(values.billed),detail:label,Icon:Receipt,color:colors[0],spark:'billed' as const},{label:'Collections',value:money(values.collected),detail:'By payment date',Icon:Wallet,color:colors[1],spark:'collected' as const},{label:'Orders in progress',value:String(active.length),detail:'Current state · all local orders',Icon:Package,color:colors[2]},{label:'Ready for delivery',value:String(ready.length),detail:'Current state · awaiting dispatch',Icon:Truck,color:colors[0]},{label:'Outstanding invoices',value:money(orders.reduce((a,o)=>a+totals(o).balance,0)),detail:'Current balance · all local invoices',Icon:CircleDollarSign,color:colors[4]}];
 return <div className={s.dashboard}>
 <div className={s.dashboardPeriod}><span>{state.branch} overview <small>Local records · not globally current</small></span><ReportingRangePicker range={range} onChange={setRange}/></div>
 <div className={s.metricCards}>{metrics.map(m=><section className={s.metricCard} key={m.label}><div className={s.metricIcon} style={{color:m.color,background:m.color+'16'}}><m.Icon size={20}/></div><div className={s.metricContent}><span>{m.label}</span><strong>{m.value.startsWith('BHD')?<><em>BHD</em>{m.value.replace(/^BHD\s*/,'')}</>:m.value}</strong><small>{m.detail}</small>{m.spark?<svg viewBox="0 0 160 48" aria-hidden="true"><polyline points={spark(m.spark)} fill="none" stroke={m.color} strokeWidth="2"/></svg>:<div className={s.metricFoot}>{m.label==='Ready for delivery'?'Ready → Dispatch → Delivered':m.label==='Orders in progress'?'Intake → Cleaning → Quality check':'Review invoices in Billing'}</div>}</div></section>)}</div>
 <div className={s.dashboardGrid}><section className={s.dashboardPanel}><header><div><h2>Billing & collections trend</h2><p>{label} · BHD</p></div><button onClick={()=>navigate('Accounting')}>View reports</button></header><div className={s.plot}><svg viewBox="0 0 650 270" role="img" aria-label={`Daily billed amounts and collections for ${state.branch}, ${label}`}>
 {[0,1,2,3,4].map(i=>{const value=ceiling*i/4;return <g key={i}><line x1="52" x2="622" y1={y(value)} y2={y(value)} stroke="#e7edef" strokeDasharray="3 5"/><text x="42" y={y(value)+4} textAnchor="end">{value.toFixed(0)}</text></g>})}
 {series.map((v,i)=><rect key={v.day} data-billed={v.billed} x={x(i)-Math.min(20,400/period)/2} y={y(v.billed)} width={Math.min(20,400/period)} height={224-y(v.billed)} rx="3" fill={colors[0]}><title>{v.day}: billed {money(v.billed)}, collected {money(v.collected)}</title></rect>)}
 <polyline points={series.map((v,i)=>`${x(i)},${y(v.collected)}`).join(' ')} fill="none" stroke={colors[1]} strokeWidth="2.5"/>{series.filter((_,i)=>period<=7||i%Math.ceil(period/6)===0||i===period-1).map(v=>{const i=days.indexOf(v.day);return <text key={v.day} x={x(i)} y="248" textAnchor="middle">{v.day.slice(5)}</text>})}
 {series.map((v,i)=><circle key={v.day} cx={x(i)} cy={y(v.collected)} r="3" fill={colors[1]}><title>{v.day}: collections {money(v.collected)}</title></circle>)}
 </svg><div className={s.legend}><span><i style={{background:colors[0]}}/>Billed</span><span><i style={{background:colors[1]}}/>Collected</span></div>{!cohort.length&&<p>No bills in this period. Change the reporting period or create an order.</p>}</div></section>
 <section className={s.dashboardPanel}><header><div><h2>Finance overview</h2><p>{label} · cash movement</p></div><button onClick={()=>navigate('Accounting')}>Open finance</button></header><div className={s.finance}>{[['Collections',values.collected],['Expenses',cost]].map(([label,value],i)=><div className={s.financeBar} key={label}><span>{label}</span><div><i style={{width:`${Number(value)/Math.max(1,values.collected,cost)*100}%`,background:colors[i]}}/></div><b>{money(Number(value))}</b></div>)}<div className={s.net}><span>Net cash movement</span><strong>{money(values.collected-cost)}</strong><small>Collections minus entered expenses</small></div></div></section>
 <section className={s.dashboardPanel}><header><div><h2>Cleaning pipeline</h2><p>Orders created {label}</p></div><button onClick={()=>navigate('Orders')}>Open orders</button></header><div className={s.pipeline}>{stages.map((stage,i)=>{const n=cohort.filter(o=>o.status===stage).length;return <div key={stage}><span><i style={{background:colors[i]}}/>{stage}</span><div className={s.pipelineTrack}><i style={{width:`${n/Math.max(1,cohort.length)*100}%`,background:colors[i]}}/></div><b>{n}</b><small>{Math.round(n/Math.max(1,cohort.length)*100)}%</small></div>})}</div></section>
 <section className={s.dashboardPanel}><header><div><h2>Service mix</h2><p>Garments in this reporting period</p></div></header><div className={s.serviceMix}><svg viewBox="0 0 160 160" role="img" aria-label={`${garments} garments by service`}><circle cx="80" cy="80" r="56" fill="none" stroke="#edf2f4" strokeWidth="18"/>{mix.map((n,i)=>{const part=n/Math.max(1,garments)*351.86;const current=offset;offset+=part;return <circle key={i} cx="80" cy="80" r="56" fill="none" stroke={colors[i]} strokeWidth="18" strokeDasharray={`${part} ${351.86-part}`} strokeDashoffset={-current} transform="rotate(-90 80 80)"/>})}<text x="80" y="80" textAnchor="middle" className={s.donutValue}>{garments}</text><text x="80" y="101" textAnchor="middle">garments</text></svg><div>{services.map((v,i)=><div className={s.mixRow} key={v.name}><span><i style={{background:colors[i]}}/>{v.name.split(' · ')[0]}</span><b>{mix[i]}</b></div>)}</div></div></section></div>
 <div className={s.dashboardGrid}><section className={s.dashboardPanel}><header><div><h2>Selected period report</h2><p>Pending is current balance on period invoices. Bahrain calendar dates · BHD</p></div><button onClick={()=>navigate('Accounting')}>View ledger</button></header><div className={s.table}><table><thead><tr><th>Period</th><th>Billed</th><th>Collected</th><th>Pending</th></tr></thead><tbody>{[[label,range.from]].map(([label,from])=>{const r=report(state,state.branch,from,days[days.length-1]);return <tr key={label}><td data-label="Period">{label}</td><td data-label="Billed">{money(r.billed)}</td><td data-label="Collected">{money(r.collected)}</td><td data-label="Pending">{money(r.pending)}</td></tr>})}</tbody></table></div></section><section className={s.dashboardPanel}><header><div><h2>Priority work queue</h2><p>{active.length} active orders in {state.branch}</p></div><button onClick={()=>navigate('Orders')}>View all</button></header><div className={s.priority}>{active.slice(0,4).map(o=><div key={o.id}><div><b>{o.id}</b><small>{state.customers.find(c=>c.id===o.customerId)?.name} · {o.status}</small></div><button onClick={()=>openOrder(o.id)}>Open order</button></div>)}{!active.length&&<p>No active orders. All local deliveries are complete.</p>}</div></section></div>
 </div>;
}
