export const KEY = 'fusion-laundry-demo-bahrain-v2';
export const branches = ['Manama', 'Riffa', 'Muharraq'] as const;
export const defaultPrefixes:Record<string,string>={Manama:'MNM',Riffa:'RFA',Muharraq:'MHQ'};
export const stages = ['Received', 'Cleaning', 'Quality check', 'Ready', 'Out for delivery', 'Delivered'] as const;
export const services = [{name:'Shirt · wash & press',price:12},{name:'Suit · dry clean',price:45},{name:'Dress · dry clean',price:35},{name:'Bedding · wash & fold',price:25}];
export type Customer = {id:string;branch:string;name:string;phone:string;address:string;notes:string};
export type Item = {service:string;quantity:number;price:number};
export type Order = {id:string;sync:'Pending'|'Synced'|'Conflict';branch:string;customerId:string;items:Item[];discount:number;tax:number;status:string;due:string;notes:string;driver:string;history:{at:string;text:string}[];payments:{id:string;amount:number;method:string;at:string}[];messages:{at:string;text:string;status:'Queued'|'Simulated online'}[]};
export type State = {version:1;branch:string;offline:boolean;invoicePrefixes:Record<string,string>;invoiceCounters:Record<string,number>;outbox:{id:string;branch:string;entity:string;recordId:string;status:'Pending'|'Synced'|'Conflict'}[];orders:Order[];customers:Customer[];expenses:{id:string;branch:string;description:string;amount:number;at:string}[]};
export const money = (n:number) => new Intl.NumberFormat('en-BH',{style:'currency',currency:'BHD'}).format(n);
export const round = (n:number) => Math.round((n+Number.EPSILON)*1000)/1000;
export const uid = () => crypto.randomUUID();
export const date = () => new Date().toISOString().slice(0,10);
export const businessDay=(at:string)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bahrain',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(at));
export function resetSamples(previous:State):State{const fresh=seed();fresh.invoicePrefixes={...previous.invoicePrefixes};fresh.invoiceCounters={...previous.invoiceCounters};for(const branch of branches){let next=previous.invoiceCounters[branch];const prefix=previous.invoicePrefixes[branch];for(const order of previous.orders){if(order.id.startsWith(prefix+'-')){const sequence=Number(order.id.slice(prefix.length+1));if(Number.isInteger(sequence))next=Math.max(next,sequence+1)}}fresh.orders=fresh.orders.map(order=>order.branch===branch?{...order,id:`${prefix}-${String(next++).padStart(5,'0')}`} : order);fresh.invoiceCounters[branch]=next}return fresh;}
export function report(state:State,branch:string,from:string,to:string){const orders=state.orders.filter(o=>o.branch===branch);const cohort=orders.filter(o=>{const d=businessDay(o.history[0].at);return d>=from&&d<=to});return {billed:round(cohort.reduce((a,o)=>a+totals(o).total,0)),collected:round(orders.reduce((a,o)=>a+o.payments.filter(p=>{const d=businessDay(p.at);return d>=from&&d<=to}).reduce((a,p)=>a+p.amount,0),0)),pending:round(cohort.reduce((a,o)=>a+totals(o).balance,0))};}
export function validState(value:unknown):value is State {
 if(!value||typeof value!=='object')return false;
 const v=value as State;const str=(x:unknown)=>typeof x==='string';const amount=(x:unknown)=>typeof x==='number'&&Number.isFinite(x)&&x>=0;const branch=(x:unknown)=>branches.some(b=>b===x);const at=(x:unknown)=>str(x)&&Number.isFinite(Date.parse(x as string));
 if(v.version!==1||typeof v.offline!=='boolean'||!v.invoicePrefixes||!v.invoiceCounters||!branches.every(b=>typeof v.invoicePrefixes[b]==='string'&&/^[A-Z0-9]{2,8}$/.test(v.invoicePrefixes[b])&&Number.isInteger(v.invoiceCounters[b])&&v.invoiceCounters[b]>0)||!Array.isArray(v.outbox)||!v.outbox.every(e=>e&&str(e.id)&&branch(e.branch)&&str(e.entity)&&str(e.recordId)&&['Pending','Synced','Conflict'].includes(e.status))||!branch(v.branch)||!Array.isArray(v.customers)||!Array.isArray(v.orders)||!Array.isArray(v.expenses))return false;
 if(!v.customers.every(c=>c&&str(c.id)&&branch(c.branch)&&str(c.name)&&str(c.phone)&&str(c.address)&&str(c.notes)))return false;
 if(new Set(v.customers.map(c=>c.id)).size!==v.customers.length||new Set(v.orders.map(o=>o?.id)).size!==v.orders.length)return false;
 if(!v.orders.every(o=>o&&str(o.id)&&['Pending','Synced','Conflict'].includes(o.sync)&&branch(o.branch)&&v.customers.some(c=>c.id===o.customerId&&c.branch===o.branch)&&stages.some(stage=>stage===o.status)&&str(o.due)&&/^\d{4}-\d{2}-\d{2}$/.test(o.due)&&str(o.notes)&&str(o.driver)&&Array.isArray(o.items)&&o.items.length>0&&o.items.every(i=>i&&str(i.service)&&Number.isInteger(i.quantity)&&i.quantity>0&&amount(i.price))&&amount(o.discount)&&o.discount<=o.items.reduce((a,i)=>a+i.quantity*i.price,0)&&amount(o.tax)&&o.tax<=100&&Array.isArray(o.history)&&o.history.length>0&&o.history.every(h=>h&&at(h.at)&&str(h.text))&&Array.isArray(o.messages)&&o.messages.every(m=>m&&at(m.at)&&str(m.text)&&['Queued','Simulated online'].includes(m.status))&&Array.isArray(o.payments)&&o.payments.every(p=>p&&str(p.id)&&amount(p.amount)&&p.amount>0&&str(p.method)&&at(p.at))&&Number.isFinite(totals(o).total)&&totals(o).balance>=0))return false;
 return v.expenses.every(e=>e&&str(e.id)&&branch(e.branch)&&str(e.description)&&amount(e.amount)&&at(e.at));
}
export function totals(o:Order) {const subtotal=round(o.items.reduce((s,i)=>s+i.quantity*i.price,0));const net=round(Math.max(0,subtotal-o.discount));const tax=round(net*o.tax/100);const total=round(net+tax);const paid=round(o.payments.reduce((s,p)=>s+p.amount,0));return {subtotal,net,tax,total,paid,balance:round(total-paid)};}
export function seed():State {const customers:Customer[]=[];const orders:Order[]=[];branches.forEach((branch,b)=>{['Amina Noor','Omar Hassan','Leila Karim','Samir Ali'].forEach((name,i)=>{const id=`c-${b}-${i}`;customers.push({id,branch,name,phone:`+973 0000 ${b}${i}00`,address:`Sample apartment ${i+1}, ${branch}, Bahrain`,notes:i===0?'Fold shirts separately. Sample preference.':''});const o:Order={id:`${defaultPrefixes[branch]}-${String(i+1).padStart(5,'0')}`,sync:'Synced',branch,customerId:id,items:[{service:services[i].name,price:services[i].price,quantity:i+2}],discount:0,tax:5,status:stages[(i+b)%6],due:date(),notes:'Synthetic demonstration order',driver:i>1?'Ravi Kumar':'',history:[{at:new Date(Date.now()-(i*8+b)*86400000).toISOString(),text:'Order received'}],payments:[],messages:[]};if(i===3)o.payments.push({id:`p-${b}`,amount:totals(o).total,method:'Card (simulated)',at:new Date().toISOString()});orders.push(o);});for(let day=1;day<=30;day++){const at=new Date(Date.now()-day*86400000).toISOString();const service=services[(day+b)%services.length];const o:Order={id:`${defaultPrefixes[branch]}-${String(day+4).padStart(5,'0')}`,sync:'Synced',branch,customerId:`c-${b}-${day%4}`,items:[{service:service.name,price:service.price,quantity:2+(day*3+b)%7}],discount:day%5===0?2:0,tax:5,status:day>5?'Delivered':stages[(day+b)%6],due:at.slice(0,10),notes:'Synthetic daily history for dashboard review',driver:'Hana Ali',history:[{at,text:'Sample order received'}],payments:[],messages:[]};if(day%4!==0)o.payments=[{id:`p-history-${b}-${day}`,amount:round(totals(o).total*(day%3===0?.5:1)),method:'Cash (simulated)',at}];orders.push(o)}});return {version:1,branch:branches[0],offline:false,invoicePrefixes:{...defaultPrefixes},invoiceCounters:Object.fromEntries(branches.map(b=>[b,35])),outbox:[],customers,orders,expenses:branches.map((branch,i)=>({id:`e-${i}`,branch,description:'Sample detergent expense',amount:35+i*10,at:new Date().toISOString()}))};}
export function message(o:Order,c:Customer) {const t=totals(o);return `Hello ${c.name},\nYour laundry invoice ${o.id} from ${o.branch} is ready for review.\n${o.items.map(i=>`${i.quantity} × ${i.service}: ${money(i.quantity*i.price)}`).join('\n')}\nSubtotal: ${money(t.subtotal)}\nDiscount: ${money(o.discount)}\nSample tax (${o.tax}%): ${money(t.tax)}\nTotal: ${money(t.total)}\nPaid: ${money(t.paid)}\nBalance: ${money(t.balance)}\nOrder status: ${o.status}\nThank you!\nDEMO PREVIEW — no message will be sent.`;}
